export const projectsData = [
    {
        id: 1,
        title: 'Rainydays',
        assignment: 'Cross-course Project',
        img: '../../resources/images/rainydays.png',
        imgAlt: 'Screenshot of Rainydays website',
        backgroundColor: 'var(--clr-rainydays)',
        textColor: 'var(--clr-white)',
        urlColor: 'invert(100%) sepia(0%) saturate(7500%) hue-rotate(241deg) brightness(100%) contrast(105%)',
        url: 'https://rainydays-andersen.netlify.app/',
        githubUrl: 'https://github.com/Noroff-FEU-Assignments/cross-course-project-anneandersen92.git',
    },
    {
        id: 2,
        title: 'Community Science Museum',
        assignment: 'Semester Project 1',
        img: '../../resources/images/science_museum.png',
        imgAlt: 'Screenshot of Community Science Museum website',
        backgroundColor: 'var(--clr-science)',
        textColor: 'var(--clr-white)',
        urlColor: 'invert(100%) sepia(0%) saturate(7500%) hue-rotate(241deg) brightness(100%) contrast(105%)',
        url: 'https://science-museum-andersen.netlify.app/',
        githubUrl: 'https://github.com/anneandersen92/semester-project-anneandersen92.git',
    },
    {
        id: 3,
        title: 'OH Sheet',
        assignment: 'Project Exam 1',
        img: '../../resources/images/ohsheet.png',
        imgAlt: 'Screenshot of OH Sheet website',
        backgroundColor: 'var(--clr-ohsheet)',
        textColor: 'var(--clr-charcoal)',
        urlColor: 'invert(15%) sepia(0%) saturate(1%) hue-rotate(159deg) brightness(95%) contrast(85%)',
        url: 'https://ohsheet-andersen.netlify.app/',
        githubUrl: 'https://github.com/anneandersen92/project-exam-1-anneandersen92.git',
    },
]